name: CI

on:
  workflow_dispatch:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y git wget texlive-xetex texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-lang-cyrillic
      - name: multimarkdown
        run: |
          git clone https://github.com/fletcher/MultiMarkdown-5.git
          cd MultiMarkdown-5
          git submodule init
          git submodule update
          make
          sudo make install

      - name: Create Artifact
        run: |
          ./release.sh

      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: metaparser
          path: release
          retention-days: 1

  upload:
    name: Create release and upload artifacts
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Create zip
        run: |
          ls -alFR
          cd metaparser
          zip -r ../metaparser.zip metaparser/
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          ./pyuploadtool-x86_64.AppImage metaparser.zip
